apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: my-new-app
    namespace: argocd
    finalizers:
        -resources-finalizer.argocd.argoproj.io
spec:
    project: default
    source:
        path: helm
        repoURL: Repo-url-to-be-provided
        targetRevision: HEAD
        helm:
            values: |
                image:
                    tag: latest
                ingress:
                    host: random-host.io
            version: v1
        destination:
            namespace: production
            server: https://kubernetes.default.svc
        syncPolicy:
            automated:
                selfHeal: true
                prune: true
        
