apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: my-second-app
    namespace: argocd
    finalizers:
        -resources-finalizer.argocd.argoproj.io
spec:
    project: default
    source:
        path: helm
        repoURL: https://github.com/vfarcic/devops-paradox.git
        targetRevision: HEAD
        helm:
            values: |
                image:
                    tag: latest
                ingress:
                    host: another-random-host.io
            version: v1
        destination:
            namespace: production
            server: https://kubernetes.default.svc
        syncPolicy:
            automated:
                selfHeal: true
                prune: true
        
